name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Prepare SQLite schema
        env:
          DATABASE_URL: file:./ci-test.db
        run: npx prisma db push --skip-generate

      - name: Run tests
        env:
          NODE_ENV: test
          DATABASE_URL: file:./ci-test.db
        run: npm test --silent

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

